language: node_js
node_js: node
services: "-mongodb"
deploy:
  provider: heroku
  api_key:
    secure: OUEnu1YHGpovBtEwuP7/lBfBI4/AubtSJds/8+aXQsccjhbLxmD7lNZaDHQB3dxAO+ahDM7IZqdDlW6/9sE+ManbimiFT2mzKnJddf0/FT9LvUdYjPgU9+fONW2dkbBGqwZqZTGDXpy+rGCW0M4zsz26qMyv+2ZMZWZ3PZvJQMPKwleadzo/p5GTFKh7RXfFX9odgXhVTHCh1PbKNXmLaGcl9KAc2rJWBLI6pksfsCHO7ixRn6U+IHmGKvF1I6avch+7toftWDH+30uVWYGZ/uVzmn3ng4NNkP3k6wMvcGT4pwaKqU7MVeFgK5EJT4dKxyiZydVazp2mXO/bYIU2/O5vQ8Zj/eEomchpSXJH2HtU2omb3DvX1HYZhjo8tskWDGMzjd5xJY69fzP5RQuRdhHu5hhuvesUKP6uANuhYrqxL2wIyrix9L2h3X9CCkpdv8yO+Bf50CsrptDZEw8TjEfVi1fkYzZ8WxrikVSLKnhHRI3js+PmMhkhOJ92tNhD8Osn8PivDzjhLQYYKKFUDg1dDHnwsP8K638hqdoMiPoLA5IgqBgGqLvxt3LCCmB0nnS5qV0Fl16w2km6ukqRpHGe3T734xhYC9VY2TsYuXD+B1NRo2WqUXxCTYTUmf/qvmCp6yqLNRJs8GAogxIRGzVDO7qvkDH6uBFlwB19AJw=
  app: protected-sierra-49309
  on:
    repo: preetha5/beetl-api
